name: Check If Code Build

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Codebase
        uses: actions/checkout@v6

      - name: Check If File Exist
        run: |
          ls -la

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      # Install NodeJS
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install dependencies
        run: pnpm install

      - name: Build Codebase
        run: pnpm run build
